"""
server.py — Phase 4: the agent as a local HTTP API.

Why a server: the VS Code extension (Phase 5) is written in TypeScript and
cannot import our Python code. It talks to this server over HTTP on
localhost instead. Nothing leaves the machine.

Run:
  uvicorn agent.server:app --port 8765
Try it:
  curl localhost:8765/health
  open http://localhost:8765/docs      (interactive API page, generated by FastAPI)

Endpoints:
  GET  /health   is the server + Ollama up? which project is indexed?
  POST /ask      question -> answer + source files
  POST /check    file -> coding-standard violations
  POST /do       task + file -> PROPOSED change (diff + new content)
  POST /fix      file -> check + PROPOSED fix

/do and /fix never leave a changed file behind: the server restores the
original and returns a proposal. The editor shows the diff and writes the
file only if the user accepts — the human stays in the loop.
"""

import contextlib
import hashlib
import os
import difflib
import io
import threading
from pathlib import Path

import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from agent import cli, config, indexer, llm, retriever, standards, tools

DEFAULT_INDEX_FILE = config.INDEX_FILE  # the CLI's index (agent_index.json)

app = FastAPI(title="Local Coding Agent", version="0.4")

# Max characters used from the open file sent with a question (keeps the 16k-token context safe).
CONTEXT_MAX_CHARS = 12000

# One agent run at a time: runs write files, two at once could clash.
agent_lock = threading.Lock()
# Set by POST /cancel; the running agent checks it after every step.
cancel_requested = threading.Event()


@app.post("/cancel")
def cancel():
    """Stop the running agent after its current step (the file is restored)."""
    if not agent_lock.locked():
        return {"cancelled": False, "detail": "No agent run in progress."}
    cancel_requested.set()
    return {"cancelled": True}


# ---------- request bodies (FastAPI validates these automatically) ----------
class ContextFile(BaseModel):
    path: str
    content: str


class AskRequest(BaseModel):
    question: str
    rerank: bool = True
    files: list[ContextFile] = []    # the file open in the editor (like Copilot)


class CheckRequest(BaseModel):
    file: str
    use_llm: bool = True


class DoRequest(BaseModel):
    task: str
    file: str
    mode: str | None = None   # "search_replace" | "add" | "auto"
    context: list[ContextFile] = []   # files the user added with "@ Context"


class ReviewRequest(BaseModel):
    file: str
    context: list[ContextFile] = []   # e.g. coding_standard.md
    focus: str = ""                   # optional: what to look for


class FixRequest(BaseModel):
    file: str
    use_llm: bool = True


# ---------- endpoints ----------
@app.get("/health")
def health():
    try:
        requests.get(f"{config.OLLAMA_URL}/api/tags", timeout=3)
        ollama = "up"
    except requests.RequestException:
        ollama = "down"
    try:
        project = load_index()["project_path"]
    except HTTPException:
        project = None
    return {"status": "ok", "ollama": ollama, "model": config.CHAT_MODEL, "project": project,
            "indexing": indexing}


@app.post("/ask")
def ask(req: AskRequest):
    index = load_index()
    chunks = retriever.retrieve(req.question, index, use_rerank=req.rerank, verbose=False)
    open_paths = {f.path for f in req.files}
    chunks = [c for c in chunks if c["path"] not in open_paths]
    if req.files:
        chunks = chunks[:2]  # the open file is the main context; keep the prompt small

    # The open file comes FIRST and in full (capped), search results after.
    parts = [f"Open file: {f.path}\n{f.content[:CONTEXT_MAX_CHARS]}" for f in req.files]
    parts += [f"File: {c['path']} (lines {c['start_line']}-{c['end_line']})\n{c['content']}" for c in chunks]
    context = "\n\n---\n\n".join(parts)
    answer = llm.chat([
        {"role": "system", "content": cli.SYSTEM_PROMPT},
        {"role": "user", "content": f"Code snippets:\n\n{context}\n\nQuestion: {req.question}"},
    ])
    sources = [{"path": f.path, "start_line": 1, "end_line": 1} for f in req.files]
    sources += [{"path": c["path"], "start_line": c["start_line"], "end_line": c["end_line"]} for c in chunks]
    return {"answer": answer, "sources": sources}


@app.post("/check")
def check(req: CheckRequest):
    project = load_index()["project_path"]
    require_file(project, req.file)
    with quiet():
        rules = standards.load_rules(project)
        violations = standards.check_file(project, req.file, rules, req.use_llm)
    return {"file": req.file, "violations": violations}


@app.post("/do")
def do(req: DoRequest):
    extra = {"extra_context": context_text(req.context)} if req.context else None
    return propose(req.task, req.file, mode=req.mode, extra_state=extra)


@app.post("/review")
def review(req: ReviewRequest):
    """Review a file against the context files (e.g. coding_standard.md).
    Returns findings with line numbers; nothing is changed."""
    project = load_index()["project_path"]
    require_file(project, req.file)
    content = tools.read_file(project, req.file)
    findings = standards.review_file(req.file, content, context_text(req.context), req.focus)
    return {"file": req.file, "findings": findings}


def context_text(files):
    """Context files as one text block (each capped to keep the prompt safe)."""
    return "\n\n".join(f"--- {f.path} ---\n{f.content[:CONTEXT_MAX_CHARS]}" for f in files)


@app.post("/fix")
def fix(req: FixRequest):
    project = load_index()["project_path"]
    require_file(project, req.file)
    with quiet():
        rules = standards.load_rules(project)
        violations = standards.check_file(project, req.file, rules, req.use_llm)
    if not violations:
        return {"file": req.file, "violations": [], "proposal": None}
    proposal = propose(standards.fix_task(violations), req.file, mode="search_replace",
                       extra_state={"allow_deletions": True})
    return {"file": req.file, "violations": violations, "proposal": proposal}


# ---------- models (like the model picker in Claude / Copilot) ----------
class ModelRequest(BaseModel):
    name: str


@app.get("/models")
def models():
    """Installed Ollama models that can chat (embedding models are hidden)."""
    try:
        tags = requests.get(f"{config.OLLAMA_URL}/api/tags", timeout=5).json()
    except requests.RequestException:
        raise HTTPException(503, "Ollama is not running. Start the Ollama app.")
    names = sorted(m["name"] for m in tags.get("models", []) if "embed" not in m["name"])
    return {"current": config.CHAT_MODEL, "models": names}


@app.post("/model")
def set_model(req: ModelRequest):
    """Switch the chat model for all following requests (not saved to config.py)."""
    if req.name not in models()["models"]:
        raise HTTPException(404, f"Model '{req.name}' is not installed. Install it first.")
    config.CHAT_MODEL = req.name
    return {"current": config.CHAT_MODEL}


@app.post("/pull")
def pull(req: ModelRequest):
    """Download a model with Ollama (can take many minutes for large models)."""
    try:
        r = requests.post(f"{config.OLLAMA_URL}/api/pull",
                          json={"model": req.name, "stream": False}, timeout=3600)
    except requests.RequestException as e:
        raise HTTPException(503, f"Ollama error: {e}")
    data = r.json()
    if r.status_code != 200 or data.get("status") != "success":
        raise HTTPException(400, data.get("error", f"Pull failed: {data}"))
    return {"installed": req.name}


# ---------- helpers ----------
def propose(task, rel_path, mode=None, extra_state=None):
    """Run the agent, capture its log, restore the file, return a proposal."""
    if not agent_lock.acquire(blocking=False):
        raise HTTPException(409, "Another agent run is in progress. Try again when it finishes.")
    old_mode = config.EDIT_MODE
    log = io.StringIO()
    cancel_requested.clear()
    try:
        if mode:
            config.EDIT_MODE = mode
        with contextlib.redirect_stdout(log):
            final = cli.execute(task, rel_path, index=load_index(), extra_state=extra_state,
                                should_stop=cancel_requested.is_set, require_clean=False)
            cli.restore(final["project_path"], rel_path, final["original"])
    except SystemExit as e:          # e.g. file missing / has uncommitted changes
        raise HTTPException(400, str(e))
    except cli.AgentCancelled:       # execute() already restored the file
        raise HTTPException(499, "Stopped by user — file unchanged.")
    finally:
        config.EDIT_MODE = old_mode
        agent_lock.release()

    new = final.get("new_content") or final["original"]
    diff = "\n".join(difflib.unified_diff(
        final["original"].splitlines(), new.splitlines(),
        fromfile=f"a/{rel_path}", tofile=f"b/{rel_path}", lineterm="",
    ))
    todos = [l.strip() for l in new.splitlines() if "TODO" in l and l not in final["original"]]
    return {
        "file": rel_path,
        "passed": bool(final.get("passed")),
        "attempts": final.get("attempts"),
        "diff": diff,
        "new_content": new,
        "todos": todos,
        "log": log.getvalue()[-4000:],
    }


def require_file(project, rel_path):
    """Clear error instead of silently treating a wrong path as an empty file."""
    try:
        exists = tools.safe_path(project, rel_path).is_file()
    except ValueError:
        exists = False
    if not exists:
        raise HTTPException(400, f"File not found in the indexed project ({project}): {rel_path}")


# ---------- projects: one index per project, built in the background ----------
# The editor tells us which project it is working in (POST /project). If that
# project has no index yet, indexing starts in a background thread right away
# and everything keeps working meanwhile with an EMPTY index (no project-wide
# search yet; Ask still sees the open file, Edit still edits the file).
INDEX_DIR = Path(__file__).parent.parent / "indexes"
_index_cache = {"file": None, "mtime": None, "data": None}
current = {"project": None}  # project the editor is working in
indexing = {"project": None, "state": "idle", "done": 0, "total": 0, "error": None}


def index_file_for(project_path):
    """indexes/<folder name>-<short hash of full path>.json — two copies of the
    same project in different folders get different indexes."""
    digest = hashlib.md5(str(project_path).encode()).hexdigest()[:8]
    return str(INDEX_DIR / f"{Path(project_path).name}-{digest}.json")


def find_index_file(project):
    """Existing index for `project`, or None."""
    if os.path.exists(index_file_for(project)):
        return index_file_for(project)
    try:  # the CLI's default index (agent_index.json) may cover this project
        if indexer.load_index_from(DEFAULT_INDEX_FILE)["project_path"] == project:
            return DEFAULT_INDEX_FILE
    except (OSError, KeyError, ValueError):
        pass
    return None


def load_index():
    """The current project's index, re-read only when the file changed
    (/health is polled every few seconds; an index can be several MB)."""
    file = config.INDEX_FILE
    if not file or not os.path.exists(file):
        if current["project"]:  # not indexed yet: work without search results
            return {"project_path": current["project"], "entries": []}
        raise HTTPException(400, "No project selected yet. Open a file from your project in VS Code.")
    mtime = os.path.getmtime(file)
    if _index_cache["file"] != file or _index_cache["mtime"] != mtime:
        _index_cache.update(file=file, mtime=mtime, data=indexer.load_index_from(file))
    return _index_cache["data"]


class ProjectRequest(BaseModel):
    project_path: str
    skip: list[str] = []


@app.post("/project")
def switch_project(req: ProjectRequest):
    """Work in this project. Not indexed yet -> start background indexing."""
    project = str(Path(req.project_path).resolve())
    if not Path(project).is_dir():
        raise HTTPException(400, f"Not a folder: {project}")
    current["project"] = project
    file = find_index_file(project)
    config.INDEX_FILE = file  # None = not indexed yet (load_index returns an empty index)
    if not file:
        start_indexing(project, req.skip)
    return {"project": project, "indexed": bool(file), "indexing": indexing}


@app.post("/index")
def reindex(req: ProjectRequest):
    """(Re)build a project's index in the background, e.g. after big changes."""
    project = str(Path(req.project_path).resolve())
    if not Path(project).is_dir():
        raise HTTPException(400, f"Not a folder: {project}")
    if not start_indexing(project, req.skip):
        raise HTTPException(409, f"Already indexing {indexing['project']}. Try again when it finishes.")
    return {"indexing": indexing}


@app.get("/index/status")
def index_status():
    return indexing


def start_indexing(project, skip):
    """Start indexing in a background thread. False if another one is running."""
    if indexing["state"] == "running":
        return indexing["project"] == project  # same project: already on it
    indexing.update(project=project, state="running", done=0, total=0, error=None)
    threading.Thread(target=_index_worker, args=(project, skip), daemon=True).start()
    return True


def _index_worker(project, skip):
    try:
        INDEX_DIR.mkdir(exist_ok=True)
        out = index_file_for(project)
        tmp = out + ".tmp"  # write to a temp file, then swap: never a half-written index
        indexer.build_index(project, skip, out_file=tmp,
                            progress=lambda done, total: indexing.update(done=done, total=total))
        os.replace(tmp, out)
        indexing.update(state="done")
        if current["project"] == project:
            config.INDEX_FILE = out  # the finished index is used from the next request
    except Exception as e:
        indexing.update(state="error", error=str(e))


@contextlib.contextmanager
def quiet():
    with contextlib.redirect_stdout(io.StringIO()):
        yield
